library:
  source-dirs: src
tests:
  hyperloglog-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hyperloglog
copyright: 2020 Author name here
maintainer: example@example.com
dependencies:
- base >= 4.7 && < 5
name: hyperloglog
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/hyperloglog
license: BSD3
executables:
  hyperloglog-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hyperloglog
description: Please see the README on GitHub at <https://github.com/githubuser/hyperloglog#readme>
